### ISSUE TITLE
"Display -> Object Types" hides map pieces based on model type, not based on object type

### ISSUE THREAD

**Issue by sonofevil** [soulsmods/DSMapStudio#348]
Steps to reproduce:

1. Enable displaying of Collision.
2. Select any piece of collision and duplicate it. Move the duplicate to a different location so you can tell it apart.
3. Go to the "ModelName" field of the new collision piece and change it to any Map Piece model (e.g. m0010B0).
4. Disable displaying of Map Pieces.

Expected result: The new collision piece appears in blue, like other collision objects.
Actual result: The new collision piece becomes invisible as if it was a Map Piece. It only appears if displaying "Map Pieces" is enabled. That's despite the fact that it says "Collision" in the "Object Type" field.

**Comment by kingborehaha** [comment]
Late reply, but yeah, you're right. The reason why is doesn't ATM is because DSMS doesn't expect an MSB part to have the wrong type of model (because Fromsoft has yet to do it in any game, and there's no reason you would ever want it either), and it would be a bit of an effort to make DSMS use object type instead. So pretty low priority.

I'll leave this open for the indefinitely since someday, somebody may feel goofy enough to do it.

**Comment by sonofevil** [comment]
Yeah I didn't really understand the relationship between models and object types when I made this report. What I really wanted was a way to convert map pieces to collision.
