### ISSUE TITLE
Ignore unsupported texture DDS type rather than crash

### ISSUE THREAD

**Issue by Grimrukh** [soulsmods/DSMapStudio#897]
Currently, DSMS crashes if it encounters a texture with a DDS type it can't read, like BC5U (even though the game may support these). It would be great if these textures could at least just be ignored. Screenshot below.

Thanks for all the hard work gang <3

![image](https://github.com/soulsmods/DSMapStudio/assets/33849304/80ee78a2-6ead-472a-89e8-13aaf4f15ff3)

**Comment by Philiquaz** [comment]
Will have to take a look. This looks like one of those places that was left as "bug to fix, we want to see these errors" rather than something we quietly ignore and never hear about.

**Comment by Philiquaz** [comment]
As of 1.11 should log texture errors instead of crashing. Feel free to reopen if something else goes wrong as a result.

**Comment by RunDevelopment** [comment]
@Philiquaz I believe this issue was fixed in #901.

Also, about the `GetPixelFormatFromFourCC` function: a few FourCC values are still missing (e.g. BC5S, which is used once in ER IIRC). I'm currently in the process of adding a new DDS decoder to a library, so [feel free to copy](https://github.com/image-rs/image/blob/ab0ec2cd79857ba902dde1b28624a1dea458fe2b/src/codecs/dds/mod.rs#L223) what I do for converting FourCC to DXGI_FORMAT.
