### ISSUE TITLE
IconID for Elden Ring

### ISSUE THREAD

**Issue by ReksRaven** [soulsmods/DSMapStudio#926]
Currently the maximum amount of digits that can be placed into the IconID field is 4.

For example I changed the ID for Caestus which is 10800. 
Now I want to change it back but cant because the most I can type in is 1080. 
Even if I want to import the row directly through CSV it tells me that the number is to large.
Kinda bad as even just clicking the Icon field will remove the 5th digit.

But maybe I am just doing smth wrong.

**Comment by Philiquaz** [comment]
Ah, looks like the same off-by-1 that chalice maps were suffering truncating the inputtext.
As a note, you'll never get larger than 65535 as that's the maximum size of the data type (and what the format and game support). Since the csv part is working on my end I can only assume that's related.
I've pushed a fix, now I have to decide on a 2nd hotfix or 1.11.2

**Comment by Philiquaz** [comment]
resolved in 1.11.1 hotfix 2

**Comment by ReksRaven** [comment]
Thank you for the quick fix o7
