### ISSUE TITLE
Problem Selecting Objects.

### ISSUE THREAD

**Issue by Ipendoot** [soulsmods/DSMapStudio#946]
Hello, I am new to DSMapStudio but have watched a few videos on how to use it. The first thing is when I select objects they aren't highlighted with an orange outline like I see in every video I have watched. So already off to a great start... The option to even move the objects isn't available except for on Pots and Trees. That is it. And even these are not highlighted. Even bushes and gravestones cannot be highlighted or moved. Yes I meet all the requirements and I also tried reinstalling Microsoft Visual C++ 2015-2019. I'm on Windows 11 64-bit. CPU is AMD Ryzen 9 7945HX and GPU is a RTX 4060. With 16GB of installed RAM. I am trying to use DSMapStudio to mod Dark Souls Remastered. Thank you for your time and I hope that we can get this sorted. Have a good day.

**Comment by Philiquaz** [comment]
Ah, looks like when we added a toggle for the selection outline (since it gets buggy with large selections) it was set to default as off. Should be in settings to re-enable that.

As for DSR, you may find that for most non-object and non-enemy things in the map, they're actually positioned at 0,0,0 and any "location" they have is a facet of the model, making the usual transform ui elements difficult to see.

**Comment by Ipendoot** [comment]
I actually just figured out how to enable the outline mode! Thanks for the reply. I still have a question though. Is the only way to move an object like the graves outside of Fire Link by manually typing in the new position? Can you not move them via click and drag with the mouse? Or in another way that is faster and less trial and error then putting in random numbers? Like for Pots I can drag them any way I want. Can I do this for the graves and objects like the graves? Sorry for all the questions. I am learning. :P Thanks!

**Comment by Philiquaz** [comment]
It'll depend on if they're part of the map geometry or are an individual object. They may be all part of the same map piece even.
Since there's no technical issues remaining (other than a reminder to change default outline setting and look into modifying where the transform ui element appears) I'm going to close the issue.
For better help getting use to using the tool and other modding questions, I recommend joining the ?servername? discord, linked in-program.
